/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function cancelTransfer(transferId: bigint): Promise<void>

export declare function closeChannel(channelId: bigint): Promise<void>

export declare function closeForward(forwardId: bigint): Promise<void>

export declare function connect(cfg: JsConnectConfig): Promise<bigint>

export declare function disconnect(sessionId: bigint): Promise<void>

export declare function forwardBoundPort(forwardId: bigint): Promise<number>

export declare function forwardLocal(sessionId: bigint, localBind: string, remoteHost: string, remotePort: number): Promise<bigint>

export declare function forwardRemote(sessionId: bigint, remoteBindHost: string, remoteBindPort: number, localHost: string, localPort: number): Promise<bigint>

export declare function forwardSocks(sessionId: bigint, localBind: string): Promise<bigint>

export declare function init(knownHostsPath: string): void

export interface JsConnectConfig {
  host: string
  port: number
  username: string
  /**
   * Exactly one of `password` or `private_key_pem` must be set.
   * Double `Option` so napi-rs decodes `null` as `None` for object fields
   * (napi-rs maps `undefined`/absent -> None but rejects `null` for
   * `Option<String>`); `.flatten()` below restores the plain type.
   */
  password?: string | undefined | null
  privateKeyPem?: string | undefined | null
  passphrase?: string | undefined | null
  connectTimeoutMs: number
  keepaliveSecs: number
}

export interface JsDirEntry {
  name: string
  size: bigint
  isDir: boolean
  isSymlink: boolean
  mode: number
  modifiedUnix: number
}

/**
 * One flat event shape rather than a tagged union, because napi object unions
 * are awkward on the JS side. `kind` discriminates; unused fields are null.
 * Plan 2 Task 3 narrows this back into a discriminated union in TypeScript.
 */
export interface JsEvent {
  kind: string
  channelId?: bigint
  sessionId?: bigint
  transferId?: bigint
  forwardId?: bigint
  bytes?: Buffer
  exitStatus?: number
  reason?: string
  done?: bigint
  total?: bigint
  error?: string
  peer?: string
  level?: string
  msg?: string
}

export declare function nextEvents(timeoutMs: number): Promise<Array<JsEvent>>

export declare function openShell(sessionId: bigint, cols: number, rows: number): Promise<bigint>

export declare function resize(channelId: bigint, cols: number, rows: number): Promise<void>

export declare function sftpDownload(sessionId: bigint, remote: string, local: string): Promise<bigint>

export declare function sftpList(sessionId: bigint, path: string): Promise<Array<JsDirEntry>>

export declare function sftpMkdir(sessionId: bigint, path: string): Promise<void>

export declare function sftpReadRange(sessionId: bigint, path: string, offset: bigint, len: number): Promise<Buffer>

export declare function sftpRemove(sessionId: bigint, path: string, recursive: boolean): Promise<void>

export declare function sftpRename(sessionId: bigint, from: string, to: string): Promise<void>

export declare function sftpStat(sessionId: bigint, path: string): Promise<JsDirEntry>

export declare function sftpUpload(sessionId: bigint, local: string, remote: string): Promise<bigint>

export declare function trustHostKey(host: string, port: number, algo: string, fingerprint: string): Promise<void>

export declare function write(channelId: bigint, data: Buffer): Promise<void>
